### ISSUE TITLE
401/403 unauthorized but pipeline test but hipchatsend works

### ISSUE THREAD

**Issue by asdf1234-deleted** [hannseman/hipsaint#45]
Printed args to stdout for review
```
hipsaint --user Operations --token SOME_ORKEN --room 'Operations' --type host --inputs "$HOSTNAME|$LONGDATETIME|$NOTIFICATIONTYPE|$HOSTADDRESS|$HOSTSTATE|$HOSTOUTPUT" -n
{'inputs': 'host.domain.com|||||', 'api_host': 'api.hipchat.com', 'msg_type': 'host', 'msg_format': 'html', 'token': 'SOME_TOKEN', 'room_id': 'Operations', 'notify': True, 'proxy': '', 'api_version': '1', 'user': 'Operations'}
[]
Traceback (most recent call last):
  File "/home/icinga/.local/share/virtualenvs/hipsaint-K_QnKhoc/bin/hipsaint", line 11, in <module>
    sys.exit(main())
  File "/home/icinga/.local/share/virtualenvs/hipsaint-K_QnKhoc/lib/python2.7/site-packages/hipsaint/bin/commands.py", line 80, in main
    msg.deliver_payload()
  File "/home/icinga/.local/share/virtualenvs/hipsaint-K_QnKhoc/lib/python2.7/site-packages/hipsaint/messages.py", line 73, in deliver_payload_v1
    raw_response = urlopen(self.urlv1, message_params)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by asdf1234-deleted** [comment]
needed full host, sorry
